Watching for file changes with StatReloader
/Users/satoso/Python/at_management/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/satoso/Python/at_management/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/satoso/Python/at_management/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/satoso/Python/at_management/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
/Users/satoso/Python/at_management/project/attendance/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/satoso/Python/at_management/project/attendance/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/satoso/Python/at_management/project/attendance/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Form invalid, errors: <ul class="errorlist"><li>recipient_number<ul class="errorlist"><li>このフィールドは必須です。</li></ul></li></ul>
Watching for file changes with StatReloader
Not Found: /favicon.ico
Checking for user with recipient number: 00007182
User found: 1
Redirecting to user-specific detail page
Internal Server Error: /home1/
Traceback (most recent call last):
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/Python/at_management/project/attendance/views.py", line 99, in get_context_data
    context['attendance_infos'] = Attendance_info.objects.filter(user=user).order_by('-calendar_date')
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1532, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1346, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/Users/satoso/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1323, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "so": Must be "User" instance.
/Users/satoso/Python/at_management/project/attendance/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Form invalid, errors: <ul class="errorlist"><li>gender<ul class="errorlist"><li>このフィールドは必須です。</li></ul></li></ul>
